# zk configuration file

[note]
filename = "untitled"
template = "default.md"

[extra]

[group.posts]
paths = ["posts"]

[group.posts.note]
filename = "{{sh 'arvelie 2020 -c today'}}-{{slug title}}"
template = "post.md"

[group.logs]
paths = ["logs"]

[group.logs.note]
filename = "{{sh 'arvelie 2020 -c today'}}"
template = "log.md"


# MARKDOWN SETTINGS
[format.markdown]
hashtags = false
colon-tags = false
multiword-tags = false

# EXTERNAL TOOLS
[tool]
[lsp]

[lsp.diagnostics]

dead-link = "error"

[lsp.completion]
[filter]

[alias]

post = "zk new posts/{{sh 'arvelie 2020 -c today | cut -c 1,2'}} --title $@"
log = "zk new logs/{{sh 'arvelie 2020 -c today | cut -c 1,2'}}" 

